### ISSUE TITLE
The `TrainerModel` class should contain only one default model

### ISSUE THREAD

**Issue by Canoming** [vindolineKis/QCircLearning#2]
Including multiple default models as `staticmethod` is confusing. We can provide these models as a subclass of `TrainerModel` and init it with `super()`.

https://github.com/vindolineKis/QCircLearning/blob/25c1983882feefe685bf0a27dec32eebd6593b10/QCircLearning/trainerModel.py#L45

**Comment by cfenglv** [comment]
Done in PR #4
