### ISSUE TITLE
Project NNQC@Qhub'team workflow

### ISSUE THREAD

**Issue by vindolineKis** [vindolineKis/QCircLearning#21]
Diagram the workflow of project management on GitHub-project. 
![Image](https://github.com/user-attachments/assets/37f6a371-681d-475d-92f1-6f1be161670f)

**Comment by vindolineKis** [comment]
Add iteration rules
![Image](https://github.com/user-attachments/assets/ce42c66a-3b0c-42e0-8f56-0343c34ade91)

**Comment by Canoming** [comment]
I created a wiki page in this project. We can put the workflow to the wiki page. It will be easier to view from there:

https://github.com/vindolineKis/QCircLearning/wiki#workflow

**Comment by vindolineKis** [comment]
🫡

**Comment by Canoming** [comment]
Included in wiki
