### ISSUE TITLE
loss can't be lower than `1e-10`

### ISSUE THREAD

**Issue by vindolineKis** [vindolineKis/QCircLearning#26]
Loss can't be lower than `1e-10` at the first iteration in 1 qubit case simulation, even using the same training model in `test_trainerModel`. The `test_trainerModel` can always be passed.

![image](https://github.com/user-attachments/assets/1e29fe8e-593c-4319-be4c-97ed4b10dca4)
![image](https://github.com/user-attachments/assets/8e37d6d4-e66d-4b79-9961-47cd184b2754)

**Comment by Canoming** [comment]
Could you create a branch and commit your code, so we can check how is it different from the test.
