### ISSUE TITLE
Improve `NN_opt`

### ISSUE THREAD

**Issue by Canoming** [vindolineKis/QCircLearning#3]
Nothing should be printed unless `verbose` is set to `True`

https://github.com/vindolineKis/QCircLearning/blob/25c1983882feefe685bf0a27dec32eebd6593b10/QCircLearning/trainerModel.py#L130-L131

https://github.com/vindolineKis/QCircLearning/blob/25c1983882feefe685bf0a27dec32eebd6593b10/QCircLearning/trainerModel.py#L134-L135

**Comment by Canoming** [comment]
Are `res.nfv = 0` necessary?

https://github.com/vindolineKis/QCircLearning/blob/25c1983882feefe685bf0a27dec32eebd6593b10/QCircLearning/trainerModel.py#L105-L107

**Comment by Canoming** [comment]
Make the assignment of `x0` a separate function, we may want to add some noises to `x0` later.

https://github.com/vindolineKis/QCircLearning/blob/25c1983882feefe685bf0a27dec32eebd6593b10/QCircLearning/trainerModel.py#L167-L171

**Comment by cfenglv** [comment]
Partial done in PR #4 except "Make the assignment of x0 a separate function, we may want to add some noises to x0 later."

**Comment by Canoming** [comment]
> Partial done in PR [#4](https://github.com/vindolineKis/QCircLearning/pull/4) except "Make the assignment of x0 a separate function, we may want to add some noises to x0 later."

Is this been implemented now?

**Comment by cfenglv** [comment]
> > Partial done in PR [#4](https://github.com/vindolineKis/QCircLearning/pull/4) except "Make the assignment of x0 a separate function, we may want to add some noises to x0 later."
> 
> Is this been implemented now?

To-do today. This issue should close and merge into issue #10
