### ISSUE TITLE
unit test for : gradients vlues?=0; fitting preformence on a few data.

### ISSUE THREAD

**Issue by vindolineKis** [vindolineKis/QCircLearning#5]
Write the unit test:
1. check the gradient values ?= 0 while fitting and searching.
2. test the fitting performance of the neural network model on a few data.

**Comment by cfenglv** [comment]
Tests add in PR #4 , with commit [587f85c](https://github.com/vindolineKis/QCircLearning/pull/4/commits/587f85ce7672e36b637a4e260a9ee3a923b1faf0)

**Comment by Canoming** [comment]
done
